on:
  workflow_run:
    workflows: ["docker-build.yml"]
    types:
      - completed
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      - name: Install Scaleway CLI
        run: |
          apt update && apt install -y curl
          curl -s https://raw.githubusercontent.com/scaleway/scaleway-cli/master/scripts/get.sh | sh

      - name: Configure Scaleway CLI
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          SCW_DEFAULT_REGION: ${{ secrets.SCW_DEFAULT_REGION }}
        run: |
          scw config set access-key $SCW_ACCESS_KEY
          scw config set secret-key $SCW_SECRET_KEY
          scw config set default-project-id $SCW_DEFAULT_PROJECT_ID
          scw config set default-region $SCW_DEFAULT_REGION

      - name: Initialize Terraform
        working-directory: ./deploy
        run: terraform init

      - name: Apply Terraform
        working-directory: ./deploy
        run: terraform apply -auto-approve
        env:
          TF_VAR_scaleway_access_key: ${{ secrets.SCW_ACCESS_KEY }}
          TF_VAR_scaleway_secret_key: ${{ secrets.SCW_SECRET_KEY }}
          TF_VAR_project_id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          TF_VAR_region: ${{ secrets.SCW_DEFAULT_REGION }}
