on:
  workflow_run:
    workflows: ["docker-build.yml"]
    types:
      - completed
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      - name: Install Scaleway CLI
        run: |
          apt update && apt install -y curl
          curl -s https://raw.githubusercontent.com/scaleway/scaleway-cli/refs/tags/v2.35.0/scripts/get.sh | sh

      - name: Configure Scaleway CLI
        run: |
          scw init -p newprofile \
            access-key=${{ secrets.SCW_ACCESS_KEY }} \
            secret-key=${{ secrets.SCW_SECRET_KEY }} \
            organization-id=${{ secrets.SCW_ORGANIZATION_ID }} \
            project-id= ${{ secrets.SCW_DEFAULT_PROJECT_ID }} \
            send-telemetry=false \
            install-autocomplete=false

      - name: Initialize Terraform
        working-directory: ./deploy
        run: terraform init

      - name: Apply Terraform
        working-directory: ./deploy
        run: terraform apply -auto-approve
        env:
          TF_VAR_scaleway_access_key: ${{ secrets.SCW_ACCESS_KEY }}
          TF_VAR_scaleway_secret_key: ${{ secrets.SCW_SECRET_KEY }}
          TF_VAR_project_id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          TF_VAR_region: ${{ secrets.SCW_DEFAULT_REGION }}
